name: vitastream
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core Flutter packages
  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # Animations & UI
  animations: ^2.0.11
  lottie: ^3.1.0
  flutter_svg: ^2.0.9
  smooth_page_indicator: ^1.2.0
  animated_background: ^2.0.0
  percent_indicator: ^4.2.5
  fluttertoast: ^8.2.8

  # BLE / IoT
  flutter_reactive_ble: ^5.3.1
  flutter_blue_plus: ^1.35.0

  # Storage & Local DB
  sqflite: ^2.4.0
  path: ^1.9.0
  path_provider: ^2.1.5
  shared_preferences: ^2.3.2
  flutter_secure_storage: ^9.0.0

  # Permissions & Notifications
  permission_handler: ^11.3.1
  flutter_local_notifications: ^19.4.0
  timezone: ^0.10.0

  # Maps & Location
  flutter_map: ^7.0.2
  google_maps_flutter: ^2.7.0
  geolocator: ^12.0.0
  url_launcher: ^6.3.0

  # HTTP / Network
  http: ^1.3.0
  provider: ^6.1.3

  # Media
  image_picker: ^1.1.2

  # Charts & Dashboard
  syncfusion_flutter_charts: ^28.1.38
  fl_chart: ^0.69.0

  connectivity_plus: ^6.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/lottie/

# Localization config
generate:
  l10n:
    arb-dir: lib/l10n
    template-arb-file: app_en.arb
    output-localization-file: app_localizations.dart
