name: vitastream
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  animations: ^2.0.11
  cupertino_icons: ^1.0.8
  flutter_reactive_ble: ^5.3.1
  sqflite: ^2.3.3
  permission_handler: ^11.3.0
  flutter_local_notifications: 19.4.0   # ✅ keep latest version
  flutter_map: ^6.0.1
  lottie: ^3.0.0
  flutter_svg: ^2.0.9
  smooth_page_indicator: ^1.1.0
  animated_background: ^2.0.0
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  url_launcher: ^6.2.5
  http: ^1.2.1   # ✅ keep latest version
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  image_picker: ^1.1.1
  flutter_blue_plus: ^1.34.3
  flutter_localizations:   # ✅ proper format
    sdk: flutter
  flutter_secure_storage: ^8.0.0
  intl: ^0.20.2

  # 🌱 New dependencies for crop irrigation dashboard
  syncfusion_flutter_charts: 30.2.6+1
  fl_chart: ^0.68.0
  fluttertoast: ^8.2.5

  # 🔹 Timezone package required for flutter_local_notifications zonedSchedule
  timezone: ^0.10.0
  percent_indicator: ^4.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true   # 🔑 required for l10n

  assets:
    - assets/images/
    - assets/lottie/
